/* Pack the Match Room worklet: bare-pack → binary .bundle → base64 TS module.
 * The bundle is passed to Worklet.start as a Uint8Array (NOT a JS string —
 * marshaling the binary-ish serialized bundle through JSI as a string
 * segfaults native-side on Android).
 *
 *   bun run pack:room
 */
import { execSync } from "child_process"
import fs from "fs"

execSync(
  "npx bare-pack --linked --host android-arm64 --host android-arm --host android-x64 --out worklet/room.bundle worklet/room.js",
  { stdio: "inherit" },
)
const bin = fs.readFileSync("worklet/room.bundle")
const b64 = bin.toString("base64")
fs.writeFileSync(
  "src/room.bundle.ts",
  `// Generated by scripts/pack-room.mjs — do not edit. (${bin.length} bytes)\nexport default\n  "${b64}"\n`,
)
fs.unlinkSync("worklet/room.bundle")
console.log(`src/room.bundle.ts written (${bin.length} bytes, base64 ${b64.length})`)
